.TH "fadecut" "1" "0.0.1"
.SH NAME
fadecut - ripping live streams, tagging and converting it to mp3 or ogg
.SH SYNOPSIS
fadecut -p [
.I profile
] [
.I OPTIONS
]
.SH DESCRIPTION
ripping live streams, tagging and converting it to mp3 or ogg
.SH OPTIONS
.B -d
Debug: -d 0|1|2|3 (level 0 is standard, -d without number is like 1)
.PP
.B -h
Show this message
.PP
.B -m
Method <sox|cutmp3>
.PP
.B -p
Profile <pop|chillout>
.PP
.B -q
Quiet
.PP
.B -s
Stream (and rip), start streamripper
.PP
.B -v
Verbose
.SH FILES
https://github.com/micressor/fadecut
.SH EXAMPLE
."Add some formatted text
.PP
fadecut -p chillout -s
