.TH "fadecut" "1" "0.0.1"
.SH NAME
fadecut - Radio livestream to ogg/mp3 tool
.SH SYNOPSIS
fadecut -p [
.I profile
] [
.I OPTIONS
]
.SH DESCRIPTION
This script handle mp3 files (-ripped by streamripper), fade in and            
out. It set stream tags: artist, title and your own decided genre.             
If you have songs you do not like, move the ripped file to dontlike/ folder,
so fadecut will no longer convert this song, if it was read on the livestream. 
All processed files of fadecut are in new/ folder. The original files of     
streamripper are in the orig/ folder after processing. 
.SH OPTIONS
.B -c
Create a new profile <profilename>
.PP
.B -e
Edit an existing profile <profilename>
.PP
.B -d
Debug: -d 0|1|2|3 (level 0 is standard, -d without number is like 1)
.PP
.B -h
Show this message
.PP
.B -m
Method <sox|split>
.PP
.B -p
Profile <profilename>
.PP
.B -q
Quiet
.PP
.B -s
Stream (and rip), start streamripper
.PP
.B -v
Verbose
.SH FILES
https://github.com/micressor/fadecut
.SH EXAMPLE
.PP
fadecut -p chillout -s
