.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.TH "fadecut" "1" "0.1.0"
.SH NAME
fadecut \- Toolset to rip audiostreams, cut, fade in/out and tag the resulting audiofiles
.SH SYNOPSIS
fadecut \-p <profile> [
.I OPTIONS
]
.SH DESCRIPTION
fadecut is a script to rip audio files from a livestream (using streamripper) and
to process them automatically. Beginning and ending fo the audio files will be 
cut and faded in/out. So logos and advertising of radio stations will be 
automatically removed.
.PP
In streaming mode fadecut is ripping audio files using streamripper. The
downloaded audio files are cutted using silence detection and then faded in and
out. Subsequently, the files are encoded to either ogg or mp3 and tagged with
tags (title, artist, genre and comment provided).
.PP
In file mode fadecut is just processing already ripped audio files.
.PP
An audio file which has already been processed is detected and will not be
processed again. Not desired songs can be stored in a separate directory. This
files are not processed anymore too.
.SH FOLDERS
fadecut is working with some standard folders. You may change them in your
profile or fadecutrc
.PP
.B done/
here you put all your songs which were already processed by fadecut and which
you want to keep. See also new/ folder.
.PP
.B dontlike/
in this folder you may put songs which you don't like. Fadecut is checking this
folder before it is processing new files in the working folder. Null size files
are ok. 
.PP
.B double/
fadecut creates null byte size files in this folder whenever it is processing a
file which is already in done/ or new/ folder.
.PP
.B error/
whenever an error occurs while fadecut is processing a file, that file is moved
to the error folder for later examining.
.PP
.B incomplete/
this folder is created by streamripper. All not fully ripped songs are saved 
here.
.PP
.B new/
processed songs are going here. Usually you may rip and process files with
fadecut, they are going in to new/ folder, you listen to them and put good songs
to the done/ folder.
.PP
.B orig/
if you want to keep the original file (which is ripped by streamripper), you may
use the \-k option. fadecut is putting the ripped files untouched into that
folder.
.PP
.SH OPTIONS
.B \-c
Create a new profile <profilename>
.PP
.B \-e
Edit an existing profile <profilename>
.PP
.B \-i
optional input <directory>
.PP
.B \-o
optional output <directory>
.PP
.B \-d
Debug: \-d 0|1|2|3 (level 0 is standard, \-d without number is like 1)
.PP
.B \-h
Show this message
.PP
.B \-p
Profile <profilename>
.PP
.B \-q
Quiet
.PP
.B \-r
Stream (and rip), start streamripper
.PP
.B \-v
Verbose
.SH VARIABLES
STREAM_URL="http://streamurl"
.RS
test
.RE
.PP
ENCODING=ogg
.RS
preferred destination fileformat. (ogg/mp3)
.RE
.PP
GENRE="SwissPop"
.RS
Processed files will get the above genre.
.RE
.PP
COMMENT="Radio Swiss Pop"
.RS
Processed files will get the above comment.
.RE
.PP
TRIM_BEGIN=0
.RS
cut <n> seconds off the file in the beginning.
.RE
.PP
TRIM_END=0
.RS
cut <n> seconds off the file at the end.
.RE
.PP
FADE_IN=1
.RS
Fade in for <n> seconds.
.RE
.PP
FADE_OUT=4
.RS
Fade out for <n> seconds.
.RE
.SH EXAMPLES
Create a new ripping profile
.RS
fadecut \-c test
.RE
.PP
Edit/update profile test
.RS
fadecut \-e test
.RE
.PP
Rip, cut and fade in\-/out with profile test
.RS
fadecut \-p test \-r
.RE
.PP
Only cut and fade in\-/out without ripping from livestream
.RS
fadecut \-p test
.RE
.PP
.SH SEE ALSO
\fBid3v2\fR(1), \fBoggenc\fR(1), \fBsox\fR(1), \fBstreamripper\fR(1),
\fBlame\fR(1)
.PP
.SH FILES
.PD 0
.TP 
.FN ~/.fadecut/fadecutrc
The main fadecut configuration file, executed with every start of fadecut
.TP
.FN ~/.fadecut/statslog.csv
The statistics file
.TP
.FN ~/.fadecut/profiles
The folder where all profiles are located
.PD
.SH RESOURCES
.TP
fadecut git website 
https://github.com/micressor/fadecut
