#!/bin/bash
#
# This file is part of fadecut
# https://github.com/micressor/fadecut
#
# fadecut is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# fadecut is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with fadecut.  If not, see <http://www.gnu.org/licenses/>.

# --- Constants ---------------------------------------------------------------
. ./config || exit 1

# Functions

function cleanup()
{
echo Cleanup...
cd -

if [ -d $HOME_FADECUT ] && [ -r /tmp/fadecut_${LOGNAME}.tar ];
then
  rm -rf ${HOME_FADECUT}
  cd /
  echo "Restoring home"
  tar xf /tmp/fadecut_${LOGNAME}.tar || retMain=3
fi
rm $LOCKFILE
echo "returnvaule=${retMain}"
exit ${retMain}
}

trap cleanup SIGHUP SIGINT SIGTERM

function prepare()
{

touch ${LOCKFILE} || exit 3

if [ -d $HOME_FADECUT ];
then					# if there is already an existing
  if tar cf /tmp/fadecut_${LOGNAME}.tar ${HOME_FADECUT};
  then
    rm -rf ${HOME_FADECUT}
    echo "Home backed up and removed"
  else
    return 3
  fi
else
  echo "no fadecut homedir, nothing to safe"
  return 3
fi

mkdir ${HOME_FADECUT}
return 0
} # prepare

function loop()
{
# loop ./recipts/*
cd ${RECIPES}
for Recipe in *.sh
do
  echo ./$Recipe $TESTFOLDER
  ./$Recipe $TESTFOLDER
  if [ $? -ge 1 ]; 
  then
    echo "$Recipe: Failed!"
    retMain=1
  else
    echo "$Recipe: Sucess!"
  fi
done
}

# Main

retMain=0
set -o pipefail

if [ -e ${LOCKFILE} ];
then
  echo "${LOCKFILE}: exists already"
  exit 1
fi

prepare
loop
cleanup
