#!/bin/bash
#
# This file is part of fadecut
# https://github.com/fadecut/fadecut
#
# fadecut is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# fadecut is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with fadecut.  If not, see <http://www.gnu.org/licenses/>.

# --- Constants ---------------------------------------------------------------
. ./config || exit 1

# Functions

trap "echo Aborting!; exit 1" SIGHUP SIGINT SIGTERM

function main()
{
# loop ./recipts/*
cd ${RECIPES}
for Recipe in *.sh
do
  echo ./$Recipe $TESTFOLDER
  ./$Recipe $TESTFOLDER
  if [ $? -ge 1 ]; 
  then
    echo "$Recipe: Failed!"
    retMain=1
  else
    echo "$Recipe: Sucess!"
  fi
done
}

# Main
set -o pipefail
main
